language: generic

services:
 - docker

env:
 - DEPENDENCY_PACKAGES="libaccountsservice-dev libgirepository1.0-dev libglib2.0-dev libgranite-dev libgtk-3-dev libwingpanel-2.0-dev meson valac"

install:
 - docker run -v "$PWD":/tmp/build-dir elementary/docker:juno-unstable /bin/sh -c "apt-get update && apt-get -y install $DEPENDENCY_PACKAGES && cd /tmp/build-dir && meson build --prefix=/usr && ninja -C build"

script:
- echo BUILDS PASSED
